services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app --timeout 120
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - USE_AWS_SECRETS=False
    depends_on:
      - db
    env_file:
      - .env
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: 1024M
    #     reservations:
    #       cpus: '0.5'
    #       memory: 512M
  db:
    image: mysql:8.0 # Le moteur Mysql RDS est en 8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
volumes:
  db_data:
