services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    #command: bash -c "python initialize_db.py && gunicorn --bind 0.0.0.0:5000 app:app"
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    env_file:
      - .env

  db:
    image: mysql:8.0 # Le moteur Mysql RDS est en 8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
volumes:
  db_data:
